version: 0.2

phases:
  pre_build:
    commands:
      - cd terraform
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply --auto-approve

  post_build:
    commands:
      - echo "Terraform apply completed on `date`"