version: 0.2

phases:
  pre_build:
    commands:
      - cd terraform
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform -chdir=ec2/ plan

  post_build:
    commands:
      - echo "Terraform plan completed on `date`"